package faithdroid

//color platte see "https://www.materialpalette.com/colors"
type ColorsCollection struct {
	Red             string
	RedLight        string
	RedDark         string
	Pink            string
	PinkLight       string
	PinkDark        string
	Purple          string
	PurpleLight     string
	PurpleDark      string
	DeepPurple      string
	DeepPurpleLight string
	DeepPurpleDark  string
	Indigo          string
	IndigoLight     string
	IndigoDark      string
	Blue            string
	BlueLight       string
	BlueDark        string
	LightBlue       string
	LightBlueLight  string
	LightBlueDark   string
	Cyan            string
	CyanLight       string
	CyanDark        string
	Teal            string
	TealLight       string
	TealDark        string
	Green           string
	GreenLight      string
	GreenDark       string
	LightGreen      string
	LightGreenLight string
	LightGreenDark  string
	Lime            string
	LimeLight       string
	LimeDark        string
	Yellow          string
	YellowLight     string
	YellowDark      string
	Amber           string
	AmberLight      string
	AmberDark       string
	Orange          string
	OrangeLight     string
	OrangeDark      string
	DeepOrange      string
	DeepOrangeLight string
	DeepOrangeDark  string
	Brown           string
	BrownLight      string
	BrownDark       string
	Grey            string
	GreyLight       string
	GreyDark        string
	BlueGrey        string
	BlueGreyLight   string
	BlueGreyDark    string
	Black, White    string
	Transparent     string
}

var colors = ColorsCollection{
	Red:             "#f44336",
	RedLight:        "#e57373",
	RedDark:         "#c62828",
	Pink:            "#e91e63",
	PinkLight:       "#f06292",
	PinkDark:        "#ad1457",
	Purple:          "#9c27b0",
	PurpleLight:     "#ba68c8",
	PurpleDark:      "#6a1b9a",
	DeepPurple:      "#673ab7",
	DeepPurpleLight: "#9575cd",
	DeepPurpleDark:  "#4527a0",
	Indigo:          "#3f51b5",
	IndigoLight:     "#7986cb",
	IndigoDark:      "#283593",
	Blue:            "#2196f3",
	BlueLight:       "#64b5f6",
	BlueDark:        "#1565c0",
	LightBlue:       "#03a9f4",
	LightBlueLight:  "#4fc3f7",
	LightBlueDark:   "#0277bd",
	Cyan:            "#00bcd4",
	CyanLight:       "#4dd0e1",
	CyanDark:        "#00838f",
	Teal:            "#009688",
	TealLight:       "#4db6ac",
	TealDark:        "#00695c",
	Green:           "#4caf50",
	GreenLight:      "#81c784",
	GreenDark:       "#2e7d32",
	LightGreen:      "#8bc34a",
	LightGreenLight: "#aed581",
	LightGreenDark:  "#558b2f",
	Lime:            "#cddc39",
	LimeLight:       "#dce775",
	LimeDark:        "#9e9d24",
	Yellow:          "#ffeb3b",
	YellowLight:     "#fff176",
	YellowDark:      "#f9a825",
	Amber:           "#ffc107",
	AmberLight:      "#ffd54f",
	AmberDark:       "#ff8f00",
	Orange:          "#ff9800",
	OrangeLight:     "#ffb74d",
	OrangeDark:      "#ef6c00",
	DeepOrange:      "#ff5722",
	DeepOrangeLight: "#ff8a65",
	DeepOrangeDark:  "#d84315",
	Brown:           "#795548",
	BrownLight:      "#a1887f",
	BrownDark:       "#4e342e",
	Grey:            "#9e9e9e",
	GreyLight:       "#e0e0e0",
	GreyDark:        "#424242",
	BlueGrey:        "#607d8b",
	BlueGreyLight:   "#90a4ae",
	BlueGreyDark:    "#37474f",
	Black:           "#000000", White: "#ffffff",
	Transparent: "#00000000",
}
