package faithdroid

//color platte see "https://www.materialpalette.com/colors"
type ColorsCollection struct {
	Red             int
	RedLight        int
	RedDark         int
	Pink            int
	PinkLight       int
	PinkDark        int
	Purple          int
	PurpleLight     int
	PurpleDark      int
	DeepPurple      int
	DeepPurpleLight int
	DeepPurpleDark  int
	Indigo          int
	IndigoLight     int
	IndigoDark      int
	Blue            int
	BlueLight       int
	BlueDark        int
	LightBlue       int
	LightBlueLight  int
	LightBlueDark   int
	Cyan            int
	CyanLight       int
	CyanDark        int
	Teal            int
	TealLight       int
	TealDark        int
	Green           int
	GreenLight      int
	GreenDark       int
	LightGreen      int
	LightGreenLight int
	LightGreenDark  int
	Lime            int
	LimeLight       int
	LimeDark        int
	Yellow          int
	YellowLight     int
	YellowDark      int
	Amber           int
	AmberLight      int
	AmberDark       int
	Orange          int
	OrangeLight     int
	OrangeDark      int
	DeepOrange      int
	DeepOrangeLight int
	DeepOrangeDark  int
	Brown           int
	BrownLight      int
	BrownDark       int
	Grey            int
	GreyLight       int
	GreyDark        int
	BlueGrey        int
	BlueGreyLight   int
	BlueGreyDark    int
	Black, White    int
	Transparent     int
}

var Colors = ColorsCollection{
	Red:             0xf44336,
	RedLight:        0xe57373,
	RedDark:         0xd32f2f,
	Pink:            0xe91e63,
	PinkLight:       0xf06292,
	PinkDark:        0xc2185b,
	Purple:          0x9c27b0,
	PurpleLight:     0xba68c8,
	PurpleDark:      0x7b1fa2,
	DeepPurple:      0x673ab7,
	DeepPurpleLight: 0x9575cd,
	DeepPurpleDark:  0x512da8,
	Indigo:          0x3f51b5,
	IndigoLight:     0x7986cb,
	IndigoDark:      0x303f9f,
	Blue:            0x2196f3,
	BlueLight:       0x64b5f6,
	BlueDark:        0x1976d2,
	LightBlue:       0x03a9f4,
	LightBlueLight:  0x4fc3f7,
	LightBlueDark:   0x0288d1,
	Cyan:            0x00bcd4,
	CyanLight:       0x4dd0e1,
	CyanDark:        0x0097a7,
	Teal:            0x009688,
	TealLight:       0x4db6ac,
	TealDark:        0x00796b,
	Green:           0x4caf50,
	GreenLight:      0x81c784,
	GreenDark:       0x388e3c,
	LightGreen:      0x8bc34a,
	LightGreenLight: 0xaed581,
	LightGreenDark:  0x689f38,
	Lime:            0xcddc39,
	LimeLight:       0xdce775,
	LimeDark:        0xafb42b,
	Yellow:          0xffeb3b,
	YellowLight:     0xfff176,
	YellowDark:      0xfbc02d,
	Amber:           0xffc107,
	AmberLight:      0xffd54f,
	AmberDark:       0xffa000,
	Orange:          0xff9800,
	OrangeLight:     0xffb74d,
	OrangeDark:      0xf57c00,
	DeepOrange:      0xff5722,
	DeepOrangeLight: 0xff8a65,
	DeepOrangeDark:  0xe64a19,
	Brown:           0x795548,
	BrownLight:      0xa1887f,
	BrownDark:       0x5d4037,
	Grey:            0x9e9e9e,
	GreyLight:       0xe0e0e0,
	GreyDark:        0x616161,
	BlueGrey:        0x607d8b,
	BlueGreyLight:   0x90a4ae,
	BlueGreyDark:    0x455a64,
	Black:           0x000000, White: 0xffffff,
	Transparent: 0x00000000,
}
