
// Objective-C API for talking to the following Go packages
//
//	github.com/gofaith/faithdroid
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Faithdroid_FRAMEWORK_H__
#define __Faithdroid_FRAMEWORK_H__

#include "Faithdroid.objc.h"
#include "universe.objc.h"

#endif
