// Objective-C API for talking to github.com/gofaith/faithdroid Go package.
//   gobind -lang=objc github.com/gofaith/faithdroid
//
// File is generated by gobind. Do not edit.

#ifndef __Faithdroid_H__
#define __Faithdroid_H__

@import Foundation;
#include "Universe.objc.h"


@class FaithdroidActivity;
@class FaithdroidActivityConfig;
@class FaithdroidApp;
@class FaithdroidColorsCollection;
@class FaithdroidFAlertDialog;
@class FaithdroidFBase;
@class FaithdroidFBaseView;
@class FaithdroidFBottomNav;
@class FaithdroidFBuild;
@class FaithdroidFButton;
@class FaithdroidFCheckBox;
@class FaithdroidFClipboard;
@class FaithdroidFEditText;
@class FaithdroidFFab;
@class FaithdroidFFrameLayout;
@class FaithdroidFHScrollView;
@class FaithdroidFImageView;
@class FaithdroidFLinearLayout;
@class FaithdroidFListView;
@class FaithdroidFMenuItem;
@class FaithdroidFPage;
@class FaithdroidFPopupMenu;
@class FaithdroidFRadioButton;
@class FaithdroidFRadioGroup;
@class FaithdroidFService;
@class FaithdroidFSnackbar;
@class FaithdroidFSpace;
@class FaithdroidFSpinner;
@class FaithdroidFSubMenu;
@class FaithdroidFSwitch;
@class FaithdroidFTab;
@class FaithdroidFTabLayout;
@class FaithdroidFTextView;
@class FaithdroidFToolbar;
@class FaithdroidFVScrollView;
@class FaithdroidFValueAnimator;
@class FaithdroidFViewPager;
@class FaithdroidFWebView;
@class FaithdroidIntent;
@class FaithdroidMainActivity;
@class FaithdroidTouchEvent;
@class FaithdroidTypeOnBindDataArgsBundle;
@class FaithdroidViewHolder;
@protocol FaithdroidIActivity;
@class FaithdroidIActivity;
@protocol FaithdroidIView;
@class FaithdroidIView;
@protocol FaithdroidUIController;
@class FaithdroidUIController;

@protocol FaithdroidIActivity <NSObject>
- (FaithdroidActivity*)getMyActivity;
@end

@protocol FaithdroidIView <NSObject>
- (NSString*)getViewId;
@end

@protocol FaithdroidUIController <NSObject>
- (void)append2RootView:(NSString*)VID;
- (FaithdroidActivity*)getCurrentFActivity;
- (NSString*)getPkg;
- (void)newView:(NSString*)viewName VID:(NSString*)VID;
- (void)runUIThread:(NSString*)fnID;
- (NSString*)viewGetAttr:(NSString*)VID attr:(NSString*)attr;
- (void)viewSetAttr:(NSString*)VID attr:(NSString*)attr value:(NSString*)value;
@end

/**
 * Activity
 */
@interface FaithdroidActivity : NSObject <goSeqRefInterface, FaithdroidIActivity> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)ui;
- (void)setUI:(NSString*)v;
// skipped field Activity.MyIntent with unsupported type: github.com/gofaith/faithdroid.Intent

- (void)addPath:(NSString*)s;
- (NSString*)getAllExtras;
- (NSString*)getContext;
- (NSString*)getExtraValue:(NSString*)key;
- (NSString*)getIntentAction;
- (FaithdroidActivity*)getMyActivity;
- (NSString*)getPathArray:(NSString*)s;
- (void)onCreate;
- (void)onDestroy;
- (void)onPause;
- (void)onResume;
- (void)onStart;
- (void)putExtra:(NSString*)key value:(NSString*)value;
- (void)setIntentAction:(NSString*)s;
- (NSString*)setUIInterface:(id<FaithdroidUIController>)u;
@end

@interface FaithdroidActivityConfig : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)myLaunchMode;
- (void)setMyLaunchMode:(NSString*)v;
- (NSString*)myFnId;
- (void)setMyFnId:(NSString*)v;
// skipped field ActivityConfig.MyIntent with unsupported type: github.com/gofaith/faithdroid.Intent

- (FaithdroidActivityConfig*)intentAction:(NSString*)s;
- (FaithdroidActivityConfig*)launchMode_SingleInstance;
- (FaithdroidActivityConfig*)launchMode_SingleTask;
- (FaithdroidActivityConfig*)launchMode_SingleTop;
- (FaithdroidActivityConfig*)launchMode_Standard;
// skipped method ActivityConfig.Paths with unsupported parameter or return types

- (FaithdroidActivityConfig*)putExtra:(NSString*)key value:(NSString*)value;
@end

@interface FaithdroidApp : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)icon;
- (void)setIcon:(NSString*)v;
- (NSString*)title;
- (void)setTitle:(NSString*)v;
- (NSString*)version;
- (void)setVersion:(NSString*)v;
- (NSString*)package;
- (void)setPackage:(NSString*)v;
- (NSString*)sourceDir;
- (void)setSourceDir:(NSString*)v;
@end

/**
 * color platte see "https://www.materialpalette.com/colors"
 */
@interface FaithdroidColorsCollection : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)red;
- (void)setRed:(NSString*)v;
- (NSString*)redLight;
- (void)setRedLight:(NSString*)v;
- (NSString*)redDark;
- (void)setRedDark:(NSString*)v;
- (NSString*)pink;
- (void)setPink:(NSString*)v;
- (NSString*)pinkLight;
- (void)setPinkLight:(NSString*)v;
- (NSString*)pinkDark;
- (void)setPinkDark:(NSString*)v;
- (NSString*)purple;
- (void)setPurple:(NSString*)v;
- (NSString*)purpleLight;
- (void)setPurpleLight:(NSString*)v;
- (NSString*)purpleDark;
- (void)setPurpleDark:(NSString*)v;
- (NSString*)deepPurple;
- (void)setDeepPurple:(NSString*)v;
- (NSString*)deepPurpleLight;
- (void)setDeepPurpleLight:(NSString*)v;
- (NSString*)deepPurpleDark;
- (void)setDeepPurpleDark:(NSString*)v;
- (NSString*)indigo;
- (void)setIndigo:(NSString*)v;
- (NSString*)indigoLight;
- (void)setIndigoLight:(NSString*)v;
- (NSString*)indigoDark;
- (void)setIndigoDark:(NSString*)v;
- (NSString*)blue;
- (void)setBlue:(NSString*)v;
- (NSString*)blueLight;
- (void)setBlueLight:(NSString*)v;
- (NSString*)blueDark;
- (void)setBlueDark:(NSString*)v;
- (NSString*)lightBlue;
- (void)setLightBlue:(NSString*)v;
- (NSString*)lightBlueLight;
- (void)setLightBlueLight:(NSString*)v;
- (NSString*)lightBlueDark;
- (void)setLightBlueDark:(NSString*)v;
- (NSString*)cyan;
- (void)setCyan:(NSString*)v;
- (NSString*)cyanLight;
- (void)setCyanLight:(NSString*)v;
- (NSString*)cyanDark;
- (void)setCyanDark:(NSString*)v;
- (NSString*)teal;
- (void)setTeal:(NSString*)v;
- (NSString*)tealLight;
- (void)setTealLight:(NSString*)v;
- (NSString*)tealDark;
- (void)setTealDark:(NSString*)v;
- (NSString*)green;
- (void)setGreen:(NSString*)v;
- (NSString*)greenLight;
- (void)setGreenLight:(NSString*)v;
- (NSString*)greenDark;
- (void)setGreenDark:(NSString*)v;
- (NSString*)lightGreen;
- (void)setLightGreen:(NSString*)v;
- (NSString*)lightGreenLight;
- (void)setLightGreenLight:(NSString*)v;
- (NSString*)lightGreenDark;
- (void)setLightGreenDark:(NSString*)v;
- (NSString*)lime;
- (void)setLime:(NSString*)v;
- (NSString*)limeLight;
- (void)setLimeLight:(NSString*)v;
- (NSString*)limeDark;
- (void)setLimeDark:(NSString*)v;
- (NSString*)yellow;
- (void)setYellow:(NSString*)v;
- (NSString*)yellowLight;
- (void)setYellowLight:(NSString*)v;
- (NSString*)yellowDark;
- (void)setYellowDark:(NSString*)v;
- (NSString*)amber;
- (void)setAmber:(NSString*)v;
- (NSString*)amberLight;
- (void)setAmberLight:(NSString*)v;
- (NSString*)amberDark;
- (void)setAmberDark:(NSString*)v;
- (NSString*)orange;
- (void)setOrange:(NSString*)v;
- (NSString*)orangeLight;
- (void)setOrangeLight:(NSString*)v;
- (NSString*)orangeDark;
- (void)setOrangeDark:(NSString*)v;
- (NSString*)deepOrange;
- (void)setDeepOrange:(NSString*)v;
- (NSString*)deepOrangeLight;
- (void)setDeepOrangeLight:(NSString*)v;
- (NSString*)deepOrangeDark;
- (void)setDeepOrangeDark:(NSString*)v;
- (NSString*)brown;
- (void)setBrown:(NSString*)v;
- (NSString*)brownLight;
- (void)setBrownLight:(NSString*)v;
- (NSString*)brownDark;
- (void)setBrownDark:(NSString*)v;
- (NSString*)grey;
- (void)setGrey:(NSString*)v;
- (NSString*)greyLight;
- (void)setGreyLight:(NSString*)v;
- (NSString*)greyDark;
- (void)setGreyDark:(NSString*)v;
- (NSString*)blueGrey;
- (void)setBlueGrey:(NSString*)v;
- (NSString*)blueGreyLight;
- (void)setBlueGreyLight:(NSString*)v;
- (NSString*)blueGreyDark;
- (void)setBlueGreyDark:(NSString*)v;
- (NSString*)black;
- (void)setBlack:(NSString*)v;
- (NSString*)white;
- (void)setWhite:(NSString*)v;
- (NSString*)transparent;
- (void)setTransparent:(NSString*)v;
- (NSString*)rippleEffect;
- (void)setRippleEffect:(NSString*)v;
@end

@interface FaithdroidFAlertDialog : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FAlertDialog.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

- (void)background:(NSString*)s;
- (void)backgroundColor:(NSString*)s;
- (void)cachedBackground:(NSString*)s;
- (void)cachedForeground:(NSString*)s;
- (void)clickable:(BOOL)b;
- (FaithdroidFAlertDialog*)dismiss;
- (void)elevation:(double)dp;
- (void)foreground:(NSString*)s;
- (NSString*)getViewId;
- (void)gone;
- (void)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (void)layoutGravity:(long)gravity;
- (void)layoutWeight:(long)f;
- (void)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FAlertDialog.NegativeButton with unsupported parameter or return types

// skipped method FAlertDialog.OnTouch with unsupported parameter or return types

- (void)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FAlertDialog.PopupMenu with unsupported parameter or return types

// skipped method FAlertDialog.PositiveButton with unsupported parameter or return types

- (FaithdroidFAlertDialog*)show;
// skipped method FAlertDialog.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFAlertDialog*)title:(NSString*)s;
- (FaithdroidFAlertDialog*)view:(id<FaithdroidIView>)iv;
- (void)visible;
@end

@interface FaithdroidFBase : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)vid;
- (void)setVID:(NSString*)v;
- (NSString*)className;
- (void)setClassName:(NSString*)v;
- (NSString*)ui;
- (void)setUI:(NSString*)v;
- (NSString*)getViewId;
@end

@interface FaithdroidFBaseView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FBaseView.FBase with unsupported type: github.com/gofaith/faithdroid.FBase

- (void)background:(NSString*)s;
- (void)backgroundColor:(NSString*)s;
- (void)cachedBackground:(NSString*)s;
- (void)cachedForeground:(NSString*)s;
- (void)clickable:(BOOL)b;
- (void)elevation:(double)dp;
- (void)foreground:(NSString*)s;
- (NSString*)getViewId;
- (void)gone;
- (void)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (void)layoutGravity:(long)gravity;
- (void)layoutWeight:(long)f;
- (void)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FBaseView.OnTouch with unsupported parameter or return types

- (void)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FBaseView.PopupMenu with unsupported parameter or return types

- (void)show;
// skipped method FBaseView.ShowPopupMenu with unsupported parameter or return types

- (void)visible;
@end

@interface FaithdroidFBottomNav : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FBottomNav.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FBottomNav.MyMenu with unsupported type: []interface{}

// skipped method FBottomNav.Assign with unsupported parameter or return types

- (FaithdroidFBottomNav*)background:(NSString*)s;
- (FaithdroidFBottomNav*)backgroundColor:(NSString*)s;
- (FaithdroidFBottomNav*)cachedBackground:(NSString*)s;
- (FaithdroidFBottomNav*)cachedForeground:(NSString*)s;
- (FaithdroidFBottomNav*)clickable:(BOOL)b;
- (FaithdroidFBottomNav*)elevation:(double)dp;
- (FaithdroidFBottomNav*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFBottomNav*)gone;
- (FaithdroidFBottomNav*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFBottomNav*)layoutGravity:(long)gravity;
- (FaithdroidFBottomNav*)layoutWeight:(long)f;
- (FaithdroidFBottomNav*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFBottomNav*)marginAll:(long)dp;
- (FaithdroidFBottomNav*)marginBottom:(long)dp;
- (FaithdroidFBottomNav*)marginLeft:(long)dp;
- (FaithdroidFBottomNav*)marginRight:(long)dp;
- (FaithdroidFBottomNav*)marginTop:(long)dp;
// skipped method FBottomNav.Menus with unsupported parameter or return types

// skipped method FBottomNav.OnClick with unsupported parameter or return types

// skipped method FBottomNav.OnTouch with unsupported parameter or return types

- (FaithdroidFBottomNav*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFBottomNav*)paddingAll:(long)all;
- (FaithdroidFBottomNav*)paddingBottom:(long)dp;
- (FaithdroidFBottomNav*)paddingLeft:(long)dp;
- (FaithdroidFBottomNav*)paddingRight:(long)dp;
- (FaithdroidFBottomNav*)paddingTop:(long)dp;
- (FaithdroidFBottomNav*)pivotX:(double)x;
- (FaithdroidFBottomNav*)pivotY:(double)y;
// skipped method FBottomNav.PopupMenu with unsupported parameter or return types

- (FaithdroidFBottomNav*)rotation:(double)r;
- (FaithdroidFBottomNav*)scaleX:(double)x;
- (FaithdroidFBottomNav*)scaleY:(double)y;
- (FaithdroidFBottomNav*)selectedItem:(long)i;
- (FaithdroidFBottomNav*)setId:(NSString*)s;
- (FaithdroidFBottomNav*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FBottomNav.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFBottomNav*)size:(long)w h:(long)h;
- (FaithdroidFBottomNav*)visible;
- (FaithdroidFBottomNav*)x:(double)x;
- (FaithdroidFBottomNav*)y:(double)y;
@end

@interface FaithdroidFBuild : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FBuild.FBase with unsupported type: github.com/gofaith/faithdroid.FBase

- (NSString*)getViewId;
- (NSString*)model;
@end

@interface FaithdroidFButton : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FButton.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FButton.Assign with unsupported parameter or return types

- (FaithdroidFButton*)background:(NSString*)s;
- (FaithdroidFButton*)backgroundColor:(NSString*)s;
- (FaithdroidFButton*)cachedBackground:(NSString*)s;
- (FaithdroidFButton*)cachedForeground:(NSString*)s;
- (FaithdroidFButton*)clickable:(BOOL)b;
- (FaithdroidFButton*)elevation:(double)dp;
- (FaithdroidFButton*)enabled:(BOOL)b;
- (FaithdroidFButton*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getText;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFButton*)gone;
- (FaithdroidFButton*)invisible;
- (BOOL)isEnabled;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFButton*)layoutGravity:(long)gravity;
- (FaithdroidFButton*)layoutWeight:(long)f;
- (FaithdroidFButton*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFButton*)marginAll:(long)dp;
- (FaithdroidFButton*)marginBottom:(long)dp;
- (FaithdroidFButton*)marginLeft:(long)dp;
- (FaithdroidFButton*)marginRight:(long)dp;
- (FaithdroidFButton*)marginTop:(long)dp;
// skipped method FButton.OnClick with unsupported parameter or return types

// skipped method FButton.OnTouch with unsupported parameter or return types

- (FaithdroidFButton*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFButton*)paddingAll:(long)dp;
- (FaithdroidFButton*)paddingBottom:(long)dp;
- (FaithdroidFButton*)paddingLeft:(long)dp;
- (FaithdroidFButton*)paddingRight:(long)dp;
- (FaithdroidFButton*)paddingTop:(long)dp;
- (FaithdroidFButton*)pivotX:(double)x;
- (FaithdroidFButton*)pivotY:(double)y;
// skipped method FButton.PopupMenu with unsupported parameter or return types

- (FaithdroidFButton*)rotation:(double)r;
- (FaithdroidFButton*)scaleX:(double)x;
- (FaithdroidFButton*)scaleY:(double)y;
- (FaithdroidFButton*)setId:(NSString*)s;
- (FaithdroidFButton*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FButton.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFButton*)size:(long)w h:(long)h;
/**
 * --------------------------------------------------------
 */
- (FaithdroidFButton*)text:(NSString*)s;
- (FaithdroidFButton*)textColor:(NSString*)s;
- (FaithdroidFButton*)textSize:(long)dpsize;
- (FaithdroidFButton*)visible;
- (FaithdroidFButton*)x:(double)x;
- (FaithdroidFButton*)y:(double)y;
@end

@interface FaithdroidFCheckBox : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FCheckBox.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FCheckBox.Assign with unsupported parameter or return types

- (FaithdroidFCheckBox*)background:(NSString*)s;
- (FaithdroidFCheckBox*)backgroundColor:(NSString*)s;
- (FaithdroidFCheckBox*)cachedBackground:(NSString*)s;
- (FaithdroidFCheckBox*)cachedForeground:(NSString*)s;
- (FaithdroidFCheckBox*)checked:(BOOL)b;
- (FaithdroidFCheckBox*)clickable:(BOOL)b;
- (FaithdroidFCheckBox*)elevation:(double)dp;
- (FaithdroidFCheckBox*)enabled:(BOOL)b;
- (FaithdroidFCheckBox*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getText;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFCheckBox*)gone;
- (FaithdroidFCheckBox*)invisible;
- (BOOL)isChecked;
- (BOOL)isEnabled;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFCheckBox*)layoutGravity:(long)gravity;
- (FaithdroidFCheckBox*)layoutWeight:(long)f;
- (FaithdroidFCheckBox*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFCheckBox*)marginAll:(long)dp;
- (FaithdroidFCheckBox*)marginBottom:(long)dp;
- (FaithdroidFCheckBox*)marginLeft:(long)dp;
- (FaithdroidFCheckBox*)marginRight:(long)dp;
- (FaithdroidFCheckBox*)marginTop:(long)dp;
// skipped method FCheckBox.OnCheckedChangeListener with unsupported parameter or return types

// skipped method FCheckBox.OnClick with unsupported parameter or return types

// skipped method FCheckBox.OnTouch with unsupported parameter or return types

- (FaithdroidFCheckBox*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFCheckBox*)paddingAll:(long)dp;
- (FaithdroidFCheckBox*)paddingBottom:(long)dp;
- (FaithdroidFCheckBox*)paddingLeft:(long)dp;
- (FaithdroidFCheckBox*)paddingRight:(long)dp;
- (FaithdroidFCheckBox*)paddingTop:(long)dp;
- (FaithdroidFCheckBox*)pivotX:(double)x;
- (FaithdroidFCheckBox*)pivotY:(double)y;
// skipped method FCheckBox.PopupMenu with unsupported parameter or return types

- (FaithdroidFCheckBox*)rotation:(double)r;
- (FaithdroidFCheckBox*)scaleX:(double)x;
- (FaithdroidFCheckBox*)scaleY:(double)y;
- (FaithdroidFCheckBox*)setId:(NSString*)s;
- (FaithdroidFCheckBox*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FCheckBox.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFCheckBox*)size:(long)w h:(long)h;
/**
 * --------------------------------------------------------
 */
- (FaithdroidFCheckBox*)text:(NSString*)s;
- (FaithdroidFCheckBox*)visible;
- (FaithdroidFCheckBox*)x:(double)x;
- (FaithdroidFCheckBox*)y:(double)y;
@end

@interface FaithdroidFClipboard : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FClipboard.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

- (void)background:(NSString*)s;
- (void)backgroundColor:(NSString*)s;
- (void)cachedBackground:(NSString*)s;
- (void)cachedForeground:(NSString*)s;
- (void)clickable:(BOOL)b;
- (FaithdroidFClipboard*)clipData:(NSString*)s;
- (void)elevation:(double)dp;
- (void)foreground:(NSString*)s;
- (long)getClipCount;
- (NSString*)getClipData;
- (NSString*)getClipDataAt:(long)index;
- (NSString*)getViewId;
- (void)gone;
- (void)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (void)layoutGravity:(long)gravity;
- (void)layoutWeight:(long)f;
- (void)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FClipboard.OnChange with unsupported parameter or return types

// skipped method FClipboard.OnTouch with unsupported parameter or return types

- (void)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FClipboard.PopupMenu with unsupported parameter or return types

- (void)show;
// skipped method FClipboard.ShowPopupMenu with unsupported parameter or return types

- (void)visible;
@end

@interface FaithdroidFEditText : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FEditText.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FEditText.Assign with unsupported parameter or return types

- (FaithdroidFEditText*)background:(NSString*)s;
- (FaithdroidFEditText*)backgroundColor:(NSString*)s;
- (FaithdroidFEditText*)cachedBackground:(NSString*)s;
- (FaithdroidFEditText*)cachedForeground:(NSString*)s;
- (FaithdroidFEditText*)clickable:(BOOL)b;
- (FaithdroidFEditText*)elevation:(double)dp;
- (FaithdroidFEditText*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getText;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFEditText*)gone;
- (FaithdroidFEditText*)hint:(NSString*)s;
- (FaithdroidFEditText*)inputTypeEnglish;
- (FaithdroidFEditText*)inputTypeNumber;
- (FaithdroidFEditText*)inputTypePassword;
- (FaithdroidFEditText*)inputTypeText;
- (FaithdroidFEditText*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFEditText*)layoutGravity:(long)gravity;
- (FaithdroidFEditText*)layoutWeight:(long)f;
- (FaithdroidFEditText*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFEditText*)marginAll:(long)dp;
- (FaithdroidFEditText*)marginBottom:(long)dp;
- (FaithdroidFEditText*)marginLeft:(long)dp;
- (FaithdroidFEditText*)marginRight:(long)dp;
- (FaithdroidFEditText*)marginTop:(long)dp;
- (FaithdroidFEditText*)maxEms:(long)i;
- (FaithdroidFEditText*)maxLength:(long)i;
- (FaithdroidFEditText*)maxLines:(long)i;
// skipped method FEditText.OnClick with unsupported parameter or return types

// skipped method FEditText.OnTouch with unsupported parameter or return types

- (FaithdroidFEditText*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFEditText*)paddingAll:(long)dp;
- (FaithdroidFEditText*)paddingBottom:(long)dp;
- (FaithdroidFEditText*)paddingLeft:(long)dp;
- (FaithdroidFEditText*)paddingRight:(long)dp;
- (FaithdroidFEditText*)paddingTop:(long)dp;
- (FaithdroidFEditText*)pivotX:(double)x;
- (FaithdroidFEditText*)pivotY:(double)y;
// skipped method FEditText.PopupMenu with unsupported parameter or return types

- (FaithdroidFEditText*)rotation:(double)r;
- (FaithdroidFEditText*)scaleX:(double)x;
- (FaithdroidFEditText*)scaleY:(double)y;
- (FaithdroidFEditText*)setId:(NSString*)s;
- (FaithdroidFEditText*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FEditText.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFEditText*)size:(long)w h:(long)h;
/**
 * --------------------------------------------------------
 */
- (FaithdroidFEditText*)text:(NSString*)s;
- (FaithdroidFEditText*)textColor:(NSString*)s;
- (FaithdroidFEditText*)textSize:(long)dpsize;
- (FaithdroidFEditText*)visible;
- (FaithdroidFEditText*)x:(double)x;
- (FaithdroidFEditText*)y:(double)y;
@end

@interface FaithdroidFFab : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FFab.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FFab.Assign with unsupported parameter or return types

- (FaithdroidFFab*)background:(NSString*)s;
- (FaithdroidFFab*)backgroundColor:(NSString*)s;
- (FaithdroidFFab*)cachedBackground:(NSString*)s;
- (FaithdroidFFab*)cachedForeground:(NSString*)s;
- (FaithdroidFFab*)clickable:(BOOL)b;
- (FaithdroidFFab*)elevation:(double)dp;
- (FaithdroidFFab*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFFab*)gone;
- (FaithdroidFFab*)icon:(NSString*)s;
- (FaithdroidFFab*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFFab*)layoutGravity:(long)gravity;
- (FaithdroidFFab*)layoutWeight:(long)f;
- (FaithdroidFFab*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFFab*)marginAll:(long)dp;
- (FaithdroidFFab*)marginBottom:(long)dp;
- (FaithdroidFFab*)marginLeft:(long)dp;
- (FaithdroidFFab*)marginRight:(long)dp;
- (FaithdroidFFab*)marginTop:(long)dp;
// skipped method FFab.OnClick with unsupported parameter or return types

// skipped method FFab.OnTouch with unsupported parameter or return types

- (FaithdroidFFab*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFFab*)paddingAll:(long)dp;
- (FaithdroidFFab*)paddingBottom:(long)dp;
- (FaithdroidFFab*)paddingLeft:(long)dp;
- (FaithdroidFFab*)paddingRight:(long)dp;
- (FaithdroidFFab*)paddingTop:(long)dp;
- (FaithdroidFFab*)pivotX:(double)x;
- (FaithdroidFFab*)pivotY:(double)y;
// skipped method FFab.PopupMenu with unsupported parameter or return types

- (FaithdroidFFab*)rotation:(double)r;
- (FaithdroidFFab*)scaleX:(double)x;
- (FaithdroidFFab*)scaleY:(double)y;
- (FaithdroidFFab*)setId:(NSString*)s;
- (FaithdroidFFab*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FFab.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFFab*)size:(long)w h:(long)h;
- (FaithdroidFFab*)visible;
- (FaithdroidFFab*)x:(double)x;
- (FaithdroidFFab*)y:(double)y;
@end

@interface FaithdroidFFrameLayout : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FFrameLayout.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FFrameLayout.Children with unsupported type: []github.com/gofaith/faithdroid.IView

- (FaithdroidFFrameLayout*)addView:(id<FaithdroidIView>)i;
- (FaithdroidFFrameLayout*)addViewAt:(id<FaithdroidIView>)i pos:(long)pos;
// skipped method FFrameLayout.Append with unsupported parameter or return types

// skipped method FFrameLayout.Assign with unsupported parameter or return types

- (FaithdroidFFrameLayout*)background:(NSString*)s;
- (FaithdroidFFrameLayout*)backgroundColor:(NSString*)s;
- (FaithdroidFFrameLayout*)cachedBackground:(NSString*)s;
- (FaithdroidFFrameLayout*)cachedForeground:(NSString*)s;
- (FaithdroidFFrameLayout*)clickable:(BOOL)b;
- (FaithdroidFFrameLayout*)deferShow;
- (FaithdroidFFrameLayout*)elevation:(double)dp;
- (FaithdroidFFrameLayout*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFFrameLayout*)gone;
- (FaithdroidFFrameLayout*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFFrameLayout*)layoutGravity:(long)gravity;
- (FaithdroidFFrameLayout*)layoutWeight:(long)f;
- (FaithdroidFFrameLayout*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFFrameLayout*)marginAll:(long)dp;
- (FaithdroidFFrameLayout*)marginBottom:(long)dp;
- (FaithdroidFFrameLayout*)marginLeft:(long)dp;
- (FaithdroidFFrameLayout*)marginRight:(long)dp;
- (FaithdroidFFrameLayout*)marginTop:(long)dp;
// skipped method FFrameLayout.OnClick with unsupported parameter or return types

// skipped method FFrameLayout.OnTouch with unsupported parameter or return types

- (FaithdroidFFrameLayout*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFFrameLayout*)paddingAll:(long)all;
- (FaithdroidFFrameLayout*)paddingBottom:(long)dp;
- (FaithdroidFFrameLayout*)paddingLeft:(long)dp;
- (FaithdroidFFrameLayout*)paddingRight:(long)dp;
- (FaithdroidFFrameLayout*)paddingTop:(long)dp;
- (FaithdroidFFrameLayout*)pivotX:(double)x;
- (FaithdroidFFrameLayout*)pivotY:(double)y;
// skipped method FFrameLayout.PopupMenu with unsupported parameter or return types

- (FaithdroidFFrameLayout*)rotation:(double)r;
- (FaithdroidFFrameLayout*)scaleX:(double)x;
- (FaithdroidFFrameLayout*)scaleY:(double)y;
- (FaithdroidFFrameLayout*)setId:(NSString*)s;
- (FaithdroidFFrameLayout*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FFrameLayout.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFFrameLayout*)size:(long)w h:(long)h;
- (FaithdroidFFrameLayout*)visible;
- (FaithdroidFFrameLayout*)x:(double)x;
- (FaithdroidFFrameLayout*)y:(double)y;
@end

@interface FaithdroidFHScrollView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FHScrollView.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FHScrollView.Children with unsupported type: []github.com/gofaith/faithdroid.IView

- (FaithdroidFHScrollView*)addView:(id<FaithdroidIView>)i;
- (FaithdroidFHScrollView*)addViewAt:(id<FaithdroidIView>)i pos:(long)pos;
// skipped method FHScrollView.Append with unsupported parameter or return types

// skipped method FHScrollView.Assign with unsupported parameter or return types

- (FaithdroidFHScrollView*)background:(NSString*)s;
- (FaithdroidFHScrollView*)backgroundColor:(NSString*)s;
- (FaithdroidFHScrollView*)cachedBackground:(NSString*)s;
- (FaithdroidFHScrollView*)cachedForeground:(NSString*)s;
- (FaithdroidFHScrollView*)clickable:(BOOL)b;
- (FaithdroidFHScrollView*)deferShow;
- (FaithdroidFHScrollView*)elevation:(double)dp;
- (FaithdroidFHScrollView*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFHScrollView*)gone;
- (FaithdroidFHScrollView*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFHScrollView*)layoutGravity:(long)gravity;
- (FaithdroidFHScrollView*)layoutWeight:(long)f;
- (FaithdroidFHScrollView*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFHScrollView*)marginAll:(long)dp;
- (FaithdroidFHScrollView*)marginBottom:(long)dp;
- (FaithdroidFHScrollView*)marginLeft:(long)dp;
- (FaithdroidFHScrollView*)marginRight:(long)dp;
- (FaithdroidFHScrollView*)marginTop:(long)dp;
// skipped method FHScrollView.OnClick with unsupported parameter or return types

// skipped method FHScrollView.OnTouch with unsupported parameter or return types

- (FaithdroidFHScrollView*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFHScrollView*)paddingAll:(long)all;
- (FaithdroidFHScrollView*)paddingBottom:(long)dp;
- (FaithdroidFHScrollView*)paddingLeft:(long)dp;
- (FaithdroidFHScrollView*)paddingRight:(long)dp;
- (FaithdroidFHScrollView*)paddingTop:(long)dp;
- (FaithdroidFHScrollView*)pivotX:(double)x;
- (FaithdroidFHScrollView*)pivotY:(double)y;
// skipped method FHScrollView.PopupMenu with unsupported parameter or return types

- (FaithdroidFHScrollView*)rotation:(double)r;
- (FaithdroidFHScrollView*)scaleX:(double)x;
- (FaithdroidFHScrollView*)scaleY:(double)y;
- (FaithdroidFHScrollView*)setId:(NSString*)s;
- (FaithdroidFHScrollView*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FHScrollView.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFHScrollView*)size:(long)w h:(long)h;
- (FaithdroidFHScrollView*)visible;
- (FaithdroidFHScrollView*)x:(double)x;
- (FaithdroidFHScrollView*)y:(double)y;
@end

@interface FaithdroidFImageView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FImageView.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FImageView.Assign with unsupported parameter or return types

- (FaithdroidFImageView*)background:(NSString*)s;
- (FaithdroidFImageView*)backgroundColor:(NSString*)s;
- (FaithdroidFImageView*)cachedBackground:(NSString*)s;
- (FaithdroidFImageView*)cachedForeground:(NSString*)s;
- (FaithdroidFImageView*)cachedSrc:(NSString*)s;
- (FaithdroidFImageView*)clickable:(BOOL)b;
- (FaithdroidFImageView*)elevation:(double)dp;
- (FaithdroidFImageView*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFImageView*)gone;
- (FaithdroidFImageView*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFImageView*)layoutGravity:(long)gravity;
- (FaithdroidFImageView*)layoutWeight:(long)f;
- (FaithdroidFImageView*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFImageView*)marginAll:(long)dp;
- (FaithdroidFImageView*)marginBottom:(long)dp;
- (FaithdroidFImageView*)marginLeft:(long)dp;
- (FaithdroidFImageView*)marginRight:(long)dp;
- (FaithdroidFImageView*)marginTop:(long)dp;
// skipped method FImageView.OnClick with unsupported parameter or return types

// skipped method FImageView.OnTouch with unsupported parameter or return types

- (FaithdroidFImageView*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFImageView*)paddingAll:(long)dp;
- (FaithdroidFImageView*)paddingBottom:(long)dp;
- (FaithdroidFImageView*)paddingLeft:(long)dp;
- (FaithdroidFImageView*)paddingRight:(long)dp;
- (FaithdroidFImageView*)paddingTop:(long)dp;
- (FaithdroidFImageView*)pivotX:(double)x;
- (FaithdroidFImageView*)pivotY:(double)y;
// skipped method FImageView.PopupMenu with unsupported parameter or return types

- (FaithdroidFImageView*)rotation:(double)r;
- (FaithdroidFImageView*)scaleType:(NSString*)s;
- (FaithdroidFImageView*)scaleX:(double)x;
- (FaithdroidFImageView*)scaleY:(double)y;
- (FaithdroidFImageView*)setId:(NSString*)s;
- (FaithdroidFImageView*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FImageView.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFImageView*)size:(long)w h:(long)h;
/**
 * --------------------------------------------------------
 */
- (FaithdroidFImageView*)src:(NSString*)s;
- (FaithdroidFImageView*)visible;
- (FaithdroidFImageView*)x:(double)x;
- (FaithdroidFImageView*)y:(double)y;
@end

@interface FaithdroidFLinearLayout : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FLinearLayout.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FLinearLayout.Children with unsupported type: []github.com/gofaith/faithdroid.IView

- (FaithdroidFLinearLayout*)addView:(id<FaithdroidIView>)i;
- (FaithdroidFLinearLayout*)addViewAt:(id<FaithdroidIView>)i pos:(long)pos;
// skipped method FLinearLayout.Append with unsupported parameter or return types

// skipped method FLinearLayout.Assign with unsupported parameter or return types

- (FaithdroidFLinearLayout*)background:(NSString*)s;
- (FaithdroidFLinearLayout*)backgroundColor:(NSString*)s;
- (FaithdroidFLinearLayout*)cachedBackground:(NSString*)s;
- (FaithdroidFLinearLayout*)cachedForeground:(NSString*)s;
- (FaithdroidFLinearLayout*)clickable:(BOOL)b;
- (FaithdroidFLinearLayout*)deferShow;
- (FaithdroidFLinearLayout*)elevation:(double)dp;
- (FaithdroidFLinearLayout*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFLinearLayout*)gone;
- (FaithdroidFLinearLayout*)horizontal;
- (FaithdroidFLinearLayout*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVertical;
- (BOOL)isVisible;
- (FaithdroidFLinearLayout*)layoutGravity:(long)gravity;
- (FaithdroidFLinearLayout*)layoutWeight:(long)f;
- (FaithdroidFLinearLayout*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFLinearLayout*)marginAll:(long)dp;
- (FaithdroidFLinearLayout*)marginBottom:(long)dp;
- (FaithdroidFLinearLayout*)marginLeft:(long)dp;
- (FaithdroidFLinearLayout*)marginRight:(long)dp;
- (FaithdroidFLinearLayout*)marginTop:(long)dp;
// skipped method FLinearLayout.OnClick with unsupported parameter or return types

// skipped method FLinearLayout.OnTouch with unsupported parameter or return types

- (FaithdroidFLinearLayout*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFLinearLayout*)paddingAll:(long)all;
- (FaithdroidFLinearLayout*)paddingBottom:(long)dp;
- (FaithdroidFLinearLayout*)paddingLeft:(long)dp;
- (FaithdroidFLinearLayout*)paddingRight:(long)dp;
- (FaithdroidFLinearLayout*)paddingTop:(long)dp;
- (FaithdroidFLinearLayout*)pivotX:(double)x;
- (FaithdroidFLinearLayout*)pivotY:(double)y;
// skipped method FLinearLayout.PopupMenu with unsupported parameter or return types

- (FaithdroidFLinearLayout*)rotation:(double)r;
- (FaithdroidFLinearLayout*)scaleX:(double)x;
- (FaithdroidFLinearLayout*)scaleY:(double)y;
- (FaithdroidFLinearLayout*)setId:(NSString*)s;
- (FaithdroidFLinearLayout*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FLinearLayout.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFLinearLayout*)size:(long)w h:(long)h;
- (FaithdroidFLinearLayout*)vertical;
- (FaithdroidFLinearLayout*)visible;
- (FaithdroidFLinearLayout*)x:(double)x;
- (FaithdroidFLinearLayout*)y:(double)y;
@end

@interface FaithdroidFListView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FListView.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FListView.Vh with unsupported type: github.com/gofaith/faithdroid.ViewHolder

// skipped method FListView.Assign with unsupported parameter or return types

- (FaithdroidFListView*)background:(NSString*)s;
- (FaithdroidFListView*)backgroundColor:(NSString*)s;
- (FaithdroidFListView*)cachedBackground:(NSString*)s;
- (FaithdroidFListView*)cachedForeground:(NSString*)s;
- (FaithdroidFListView*)clickable:(BOOL)b;
- (FaithdroidFListView*)elevation:(double)dp;
- (FaithdroidFListView*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFListView*)gone;
- (FaithdroidFListView*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFListView*)layoutGravity:(long)gravity;
- (FaithdroidFListView*)layoutWeight:(long)f;
- (FaithdroidFListView*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFListView*)marginAll:(long)dp;
- (FaithdroidFListView*)marginBottom:(long)dp;
- (FaithdroidFListView*)marginLeft:(long)dp;
- (FaithdroidFListView*)marginRight:(long)dp;
- (FaithdroidFListView*)marginTop:(long)dp;
/**
 * --------------------------------------------------------------------
 */
- (FaithdroidFListView*)notifyDataSetChanged;
// skipped method FListView.OnClick with unsupported parameter or return types

// skipped method FListView.OnTouch with unsupported parameter or return types

- (FaithdroidFListView*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFListView*)paddingAll:(long)all;
- (FaithdroidFListView*)paddingBottom:(long)dp;
- (FaithdroidFListView*)paddingLeft:(long)dp;
- (FaithdroidFListView*)paddingRight:(long)dp;
- (FaithdroidFListView*)paddingTop:(long)dp;
- (FaithdroidFListView*)pivotX:(double)x;
- (FaithdroidFListView*)pivotY:(double)y;
// skipped method FListView.PopupMenu with unsupported parameter or return types

- (FaithdroidFListView*)rotation:(double)r;
- (FaithdroidFListView*)scaleX:(double)x;
- (FaithdroidFListView*)scaleY:(double)y;
/**
 * -----------------------------------
 */
- (FaithdroidFListView*)setId:(NSString*)s;
- (FaithdroidFListView*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FListView.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFListView*)size:(long)w h:(long)h;
- (FaithdroidFListView*)visible;
- (FaithdroidFListView*)x:(double)x;
- (FaithdroidFListView*)y:(double)y;
@end

@interface FaithdroidFMenuItem : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)myTitle;
- (void)setMyTitle:(NSString*)v;
- (NSString*)myIcon;
- (void)setMyIcon:(NSString*)v;
- (NSString*)myOnClick;
- (void)setMyOnClick:(NSString*)v;
- (NSString*)myShowAsAction;
- (void)setMyShowAsAction:(NSString*)v;
- (FaithdroidFMenuItem*)icon:(NSString*)s;
// skipped method FMenuItem.OnClick with unsupported parameter or return types

- (FaithdroidFMenuItem*)showAsAction;
@end

/**
 * --------------------------------------------------------
 */
@interface FaithdroidFPage : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)vid;
- (void)setVID:(NSString*)v;
@end

@interface FaithdroidFPopupMenu : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)vid;
- (void)setVID:(NSString*)v;
- (NSString*)className;
- (void)setClassName:(NSString*)v;
- (NSString*)ui;
- (void)setUI:(NSString*)v;
- (FaithdroidFPopupMenu*)dismiss;
- (NSString*)getViewId;
- (FaithdroidFPopupMenu*)show;
@end

@interface FaithdroidFRadioButton : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FRadioButton.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FRadioButton.Assign with unsupported parameter or return types

- (FaithdroidFRadioButton*)background:(NSString*)s;
- (FaithdroidFRadioButton*)backgroundColor:(NSString*)s;
- (FaithdroidFRadioButton*)cachedBackground:(NSString*)s;
- (FaithdroidFRadioButton*)cachedForeground:(NSString*)s;
- (FaithdroidFRadioButton*)clickable:(BOOL)b;
- (FaithdroidFRadioButton*)elevation:(double)dp;
- (FaithdroidFRadioButton*)enabled:(BOOL)b;
- (FaithdroidFRadioButton*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getText;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFRadioButton*)gone;
- (FaithdroidFRadioButton*)invisible;
- (BOOL)isEnabled;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFRadioButton*)layoutGravity:(long)gravity;
- (FaithdroidFRadioButton*)layoutWeight:(long)f;
- (FaithdroidFRadioButton*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFRadioButton*)marginAll:(long)dp;
- (FaithdroidFRadioButton*)marginBottom:(long)dp;
- (FaithdroidFRadioButton*)marginLeft:(long)dp;
- (FaithdroidFRadioButton*)marginRight:(long)dp;
- (FaithdroidFRadioButton*)marginTop:(long)dp;
// skipped method FRadioButton.OnClick with unsupported parameter or return types

// skipped method FRadioButton.OnTouch with unsupported parameter or return types

- (FaithdroidFRadioButton*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFRadioButton*)paddingAll:(long)dp;
- (FaithdroidFRadioButton*)paddingBottom:(long)dp;
- (FaithdroidFRadioButton*)paddingLeft:(long)dp;
- (FaithdroidFRadioButton*)paddingRight:(long)dp;
- (FaithdroidFRadioButton*)paddingTop:(long)dp;
- (FaithdroidFRadioButton*)pivotX:(double)x;
- (FaithdroidFRadioButton*)pivotY:(double)y;
// skipped method FRadioButton.PopupMenu with unsupported parameter or return types

- (FaithdroidFRadioButton*)rotation:(double)r;
- (FaithdroidFRadioButton*)scaleX:(double)x;
- (FaithdroidFRadioButton*)scaleY:(double)y;
- (FaithdroidFRadioButton*)setId:(NSString*)s;
- (FaithdroidFRadioButton*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FRadioButton.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFRadioButton*)size:(long)w h:(long)h;
/**
 * --------------------------------------------------------
 */
- (FaithdroidFRadioButton*)text:(NSString*)s;
- (FaithdroidFRadioButton*)textColor:(NSString*)s;
- (FaithdroidFRadioButton*)textSize:(long)dpsize;
- (FaithdroidFRadioButton*)visible;
- (FaithdroidFRadioButton*)x:(double)x;
- (FaithdroidFRadioButton*)y:(double)y;
@end

@interface FaithdroidFRadioGroup : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FRadioGroup.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FRadioGroup.Children with unsupported type: []*github.com/gofaith/faithdroid.FRadioButton

// skipped method FRadioGroup.Append with unsupported parameter or return types

// skipped method FRadioGroup.Assign with unsupported parameter or return types

- (FaithdroidFRadioGroup*)background:(NSString*)s;
- (FaithdroidFRadioGroup*)backgroundColor:(NSString*)s;
- (FaithdroidFRadioGroup*)cachedBackground:(NSString*)s;
- (FaithdroidFRadioGroup*)cachedForeground:(NSString*)s;
- (FaithdroidFRadioGroup*)clickable:(BOOL)b;
- (FaithdroidFRadioGroup*)elevation:(double)dp;
- (FaithdroidFRadioGroup*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFRadioGroup*)gone;
- (FaithdroidFRadioGroup*)horizontal;
- (FaithdroidFRadioGroup*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVertical;
- (BOOL)isVisible;
- (FaithdroidFRadioGroup*)layoutGravity:(long)gravity;
- (FaithdroidFRadioGroup*)layoutWeight:(long)f;
- (FaithdroidFRadioGroup*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFRadioGroup*)marginAll:(long)dp;
- (FaithdroidFRadioGroup*)marginBottom:(long)dp;
- (FaithdroidFRadioGroup*)marginLeft:(long)dp;
- (FaithdroidFRadioGroup*)marginRight:(long)dp;
- (FaithdroidFRadioGroup*)marginTop:(long)dp;
// skipped method FRadioGroup.OnCheckedChange with unsupported parameter or return types

// skipped method FRadioGroup.OnClick with unsupported parameter or return types

// skipped method FRadioGroup.OnTouch with unsupported parameter or return types

- (FaithdroidFRadioGroup*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFRadioGroup*)paddingAll:(long)all;
- (FaithdroidFRadioGroup*)paddingBottom:(long)dp;
- (FaithdroidFRadioGroup*)paddingLeft:(long)dp;
- (FaithdroidFRadioGroup*)paddingRight:(long)dp;
- (FaithdroidFRadioGroup*)paddingTop:(long)dp;
- (FaithdroidFRadioGroup*)pivotX:(double)x;
- (FaithdroidFRadioGroup*)pivotY:(double)y;
// skipped method FRadioGroup.PopupMenu with unsupported parameter or return types

- (FaithdroidFRadioGroup*)rotation:(double)r;
- (FaithdroidFRadioGroup*)scaleX:(double)x;
- (FaithdroidFRadioGroup*)scaleY:(double)y;
- (FaithdroidFRadioGroup*)setId:(NSString*)s;
- (FaithdroidFRadioGroup*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FRadioGroup.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFRadioGroup*)size:(long)w h:(long)h;
- (FaithdroidFRadioGroup*)vertical;
- (FaithdroidFRadioGroup*)visible;
- (FaithdroidFRadioGroup*)x:(double)x;
- (FaithdroidFRadioGroup*)y:(double)y;
@end

@interface FaithdroidFService : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)getContext;
@end

@interface FaithdroidFSnackbar : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FSnackbar.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FSnackbar.Action with unsupported parameter or return types

- (void)background:(NSString*)s;
- (void)backgroundColor:(NSString*)s;
- (void)cachedBackground:(NSString*)s;
- (void)cachedForeground:(NSString*)s;
- (void)clickable:(BOOL)b;
- (void)elevation:(double)dp;
- (void)foreground:(NSString*)s;
- (NSString*)getViewId;
- (void)gone;
- (void)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (void)layoutGravity:(long)gravity;
- (void)layoutWeight:(long)f;
- (void)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FSnackbar.OnTouch with unsupported parameter or return types

- (void)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
// skipped method FSnackbar.PopupMenu with unsupported parameter or return types

- (void)show;
// skipped method FSnackbar.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFSnackbar*)text:(NSString*)s;
- (void)visible;
@end

@interface FaithdroidFSpace : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FSpace.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FSpace.Assign with unsupported parameter or return types

- (FaithdroidFSpace*)background:(NSString*)s;
- (FaithdroidFSpace*)backgroundColor:(NSString*)s;
- (FaithdroidFSpace*)cachedBackground:(NSString*)s;
- (FaithdroidFSpace*)cachedForeground:(NSString*)s;
- (FaithdroidFSpace*)clickable:(BOOL)b;
- (FaithdroidFSpace*)elevation:(double)dp;
- (FaithdroidFSpace*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFSpace*)gone;
- (FaithdroidFSpace*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFSpace*)layoutGravity:(long)gravity;
- (FaithdroidFSpace*)layoutWeight:(long)f;
- (FaithdroidFSpace*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFSpace*)marginAll:(long)dp;
- (FaithdroidFSpace*)marginBottom:(long)dp;
- (FaithdroidFSpace*)marginLeft:(long)dp;
- (FaithdroidFSpace*)marginRight:(long)dp;
- (FaithdroidFSpace*)marginTop:(long)dp;
// skipped method FSpace.OnClick with unsupported parameter or return types

// skipped method FSpace.OnTouch with unsupported parameter or return types

- (FaithdroidFSpace*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFSpace*)paddingAll:(long)dp;
- (FaithdroidFSpace*)paddingBottom:(long)dp;
- (FaithdroidFSpace*)paddingLeft:(long)dp;
- (FaithdroidFSpace*)paddingRight:(long)dp;
- (FaithdroidFSpace*)paddingTop:(long)dp;
- (FaithdroidFSpace*)pivotX:(double)x;
- (FaithdroidFSpace*)pivotY:(double)y;
// skipped method FSpace.PopupMenu with unsupported parameter or return types

- (FaithdroidFSpace*)rotation:(double)r;
- (FaithdroidFSpace*)scaleX:(double)x;
- (FaithdroidFSpace*)scaleY:(double)y;
- (FaithdroidFSpace*)setId:(NSString*)s;
- (FaithdroidFSpace*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FSpace.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFSpace*)size:(long)w h:(long)h;
- (FaithdroidFSpace*)visible;
- (FaithdroidFSpace*)x:(double)x;
- (FaithdroidFSpace*)y:(double)y;
@end

@interface FaithdroidFSpinner : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FSpinner.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FSpinner.Assign with unsupported parameter or return types

- (FaithdroidFSpinner*)background:(NSString*)s;
- (FaithdroidFSpinner*)backgroundColor:(NSString*)s;
- (FaithdroidFSpinner*)cachedBackground:(NSString*)s;
- (FaithdroidFSpinner*)cachedForeground:(NSString*)s;
- (FaithdroidFSpinner*)clickable:(BOOL)b;
- (FaithdroidFSpinner*)elevation:(double)dp;
- (FaithdroidFSpinner*)enabled:(BOOL)b;
- (FaithdroidFSpinner*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFSpinner*)gone;
- (FaithdroidFSpinner*)invisible;
- (BOOL)isEnabled;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFSpinner*)layoutGravity:(long)gravity;
- (FaithdroidFSpinner*)layoutWeight:(long)f;
// skipped method FSpinner.List with unsupported parameter or return types

- (FaithdroidFSpinner*)listAdd:(NSString*)s;
- (FaithdroidFSpinner*)listRemove:(long)i;
- (FaithdroidFSpinner*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFSpinner*)marginAll:(long)dp;
- (FaithdroidFSpinner*)marginBottom:(long)dp;
- (FaithdroidFSpinner*)marginLeft:(long)dp;
- (FaithdroidFSpinner*)marginRight:(long)dp;
- (FaithdroidFSpinner*)marginTop:(long)dp;
- (FaithdroidFSpinner*)notifyDataSetChanged;
// skipped method FSpinner.OnClick with unsupported parameter or return types

// skipped method FSpinner.OnItemClick with unsupported parameter or return types

// skipped method FSpinner.OnTouch with unsupported parameter or return types

- (FaithdroidFSpinner*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFSpinner*)paddingAll:(long)dp;
- (FaithdroidFSpinner*)paddingBottom:(long)dp;
- (FaithdroidFSpinner*)paddingLeft:(long)dp;
- (FaithdroidFSpinner*)paddingRight:(long)dp;
- (FaithdroidFSpinner*)paddingTop:(long)dp;
- (FaithdroidFSpinner*)pivotX:(double)x;
- (FaithdroidFSpinner*)pivotY:(double)y;
// skipped method FSpinner.PopupMenu with unsupported parameter or return types

- (FaithdroidFSpinner*)rotation:(double)r;
- (FaithdroidFSpinner*)scaleX:(double)x;
- (FaithdroidFSpinner*)scaleY:(double)y;
- (FaithdroidFSpinner*)setId:(NSString*)s;
- (FaithdroidFSpinner*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FSpinner.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFSpinner*)size:(long)w h:(long)h;
- (FaithdroidFSpinner*)visible;
- (FaithdroidFSpinner*)x:(double)x;
- (FaithdroidFSpinner*)y:(double)y;
@end

@interface FaithdroidFSubMenu : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)myTitle;
- (void)setMyTitle:(NSString*)v;
// skipped field FSubMenu.MySubMenu with unsupported type: []interface{}

@end

@interface FaithdroidFSwitch : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FSwitch.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FSwitch.Assign with unsupported parameter or return types

- (FaithdroidFSwitch*)background:(NSString*)s;
- (FaithdroidFSwitch*)backgroundColor:(NSString*)s;
- (FaithdroidFSwitch*)cachedBackground:(NSString*)s;
- (FaithdroidFSwitch*)cachedForeground:(NSString*)s;
- (FaithdroidFSwitch*)checked:(BOOL)b;
- (FaithdroidFSwitch*)clickable:(BOOL)b;
- (FaithdroidFSwitch*)elevation:(double)dp;
/**
 * --------------------------------------------------------
 */
- (FaithdroidFSwitch*)enabled:(BOOL)b;
- (FaithdroidFSwitch*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFSwitch*)gone;
- (FaithdroidFSwitch*)invisible;
- (BOOL)isChecked;
- (BOOL)isEnabled;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFSwitch*)layoutGravity:(long)gravity;
- (FaithdroidFSwitch*)layoutWeight:(long)f;
- (FaithdroidFSwitch*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFSwitch*)marginAll:(long)dp;
- (FaithdroidFSwitch*)marginBottom:(long)dp;
- (FaithdroidFSwitch*)marginLeft:(long)dp;
- (FaithdroidFSwitch*)marginRight:(long)dp;
- (FaithdroidFSwitch*)marginTop:(long)dp;
// skipped method FSwitch.OnCheckedChangeListener with unsupported parameter or return types

// skipped method FSwitch.OnClick with unsupported parameter or return types

// skipped method FSwitch.OnTouch with unsupported parameter or return types

- (FaithdroidFSwitch*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFSwitch*)paddingAll:(long)dp;
- (FaithdroidFSwitch*)paddingBottom:(long)dp;
- (FaithdroidFSwitch*)paddingLeft:(long)dp;
- (FaithdroidFSwitch*)paddingRight:(long)dp;
- (FaithdroidFSwitch*)paddingTop:(long)dp;
- (FaithdroidFSwitch*)pivotX:(double)x;
- (FaithdroidFSwitch*)pivotY:(double)y;
// skipped method FSwitch.PopupMenu with unsupported parameter or return types

- (FaithdroidFSwitch*)rotation:(double)r;
- (FaithdroidFSwitch*)scaleX:(double)x;
- (FaithdroidFSwitch*)scaleY:(double)y;
- (FaithdroidFSwitch*)setId:(NSString*)s;
- (FaithdroidFSwitch*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FSwitch.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFSwitch*)size:(long)w h:(long)h;
- (FaithdroidFSwitch*)visible;
- (FaithdroidFSwitch*)x:(double)x;
- (FaithdroidFSwitch*)y:(double)y;
@end

@interface FaithdroidFTab : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)text;
- (void)setText:(NSString*)v;
- (NSString*)icon;
- (void)setIcon:(NSString*)v;
- (FaithdroidFTab*)iconSrc:(NSString*)s;
@end

@interface FaithdroidFTabLayout : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FTabLayout.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FTabLayout.Assign with unsupported parameter or return types

- (FaithdroidFTabLayout*)background:(NSString*)s;
- (FaithdroidFTabLayout*)backgroundColor:(NSString*)s;
- (FaithdroidFTabLayout*)cachedBackground:(NSString*)s;
- (FaithdroidFTabLayout*)cachedForeground:(NSString*)s;
- (FaithdroidFTabLayout*)clickable:(BOOL)b;
- (FaithdroidFTabLayout*)elevation:(double)dp;
- (FaithdroidFTabLayout*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFTabLayout*)gone;
- (FaithdroidFTabLayout*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFTabLayout*)layoutGravity:(long)gravity;
- (FaithdroidFTabLayout*)layoutWeight:(long)f;
- (FaithdroidFTabLayout*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFTabLayout*)marginAll:(long)dp;
- (FaithdroidFTabLayout*)marginBottom:(long)dp;
- (FaithdroidFTabLayout*)marginLeft:(long)dp;
- (FaithdroidFTabLayout*)marginRight:(long)dp;
- (FaithdroidFTabLayout*)marginTop:(long)dp;
// skipped method FTabLayout.OnClick with unsupported parameter or return types

// skipped method FTabLayout.OnTouch with unsupported parameter or return types

- (FaithdroidFTabLayout*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFTabLayout*)paddingAll:(long)all;
- (FaithdroidFTabLayout*)paddingBottom:(long)dp;
- (FaithdroidFTabLayout*)paddingLeft:(long)dp;
- (FaithdroidFTabLayout*)paddingRight:(long)dp;
- (FaithdroidFTabLayout*)paddingTop:(long)dp;
- (FaithdroidFTabLayout*)pivotX:(double)x;
- (FaithdroidFTabLayout*)pivotY:(double)y;
// skipped method FTabLayout.PopupMenu with unsupported parameter or return types

- (FaithdroidFTabLayout*)rotation:(double)r;
- (FaithdroidFTabLayout*)scaleX:(double)x;
- (FaithdroidFTabLayout*)scaleY:(double)y;
- (FaithdroidFTabLayout*)setId:(NSString*)s;
- (FaithdroidFTabLayout*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FTabLayout.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFTabLayout*)size:(long)w h:(long)h;
// skipped method FTabLayout.Tabs with unsupported parameter or return types

- (FaithdroidFTabLayout*)visible;
- (FaithdroidFTabLayout*)x:(double)x;
- (FaithdroidFTabLayout*)y:(double)y;
@end

@interface FaithdroidFTextView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FTextView.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FTextView.Assign with unsupported parameter or return types

- (FaithdroidFTextView*)background:(NSString*)s;
- (FaithdroidFTextView*)backgroundColor:(NSString*)s;
- (FaithdroidFTextView*)cachedBackground:(NSString*)s;
- (FaithdroidFTextView*)cachedForeground:(NSString*)s;
- (FaithdroidFTextView*)clickable:(BOOL)b;
- (FaithdroidFTextView*)elevation:(double)dp;
- (FaithdroidFTextView*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getText;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFTextView*)gone;
- (FaithdroidFTextView*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFTextView*)layoutGravity:(long)gravity;
- (FaithdroidFTextView*)layoutWeight:(long)f;
- (FaithdroidFTextView*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFTextView*)marginAll:(long)dp;
- (FaithdroidFTextView*)marginBottom:(long)dp;
- (FaithdroidFTextView*)marginLeft:(long)dp;
- (FaithdroidFTextView*)marginRight:(long)dp;
- (FaithdroidFTextView*)marginTop:(long)dp;
// skipped method FTextView.OnClick with unsupported parameter or return types

// skipped method FTextView.OnTouch with unsupported parameter or return types

- (FaithdroidFTextView*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFTextView*)paddingAll:(long)all;
- (FaithdroidFTextView*)paddingBottom:(long)dp;
- (FaithdroidFTextView*)paddingLeft:(long)dp;
- (FaithdroidFTextView*)paddingRight:(long)dp;
- (FaithdroidFTextView*)paddingTop:(long)dp;
- (FaithdroidFTextView*)pivotX:(double)x;
- (FaithdroidFTextView*)pivotY:(double)y;
// skipped method FTextView.PopupMenu with unsupported parameter or return types

- (FaithdroidFTextView*)rotation:(double)r;
- (FaithdroidFTextView*)scaleX:(double)x;
- (FaithdroidFTextView*)scaleY:(double)y;
- (FaithdroidFTextView*)setId:(NSString*)s;
- (FaithdroidFTextView*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FTextView.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFTextView*)size:(long)w h:(long)h;
/**
 * --------------------------------------------------------
 */
- (FaithdroidFTextView*)text:(NSString*)s;
- (FaithdroidFTextView*)textColor:(NSString*)s;
- (FaithdroidFTextView*)textSize:(long)dpsize;
- (FaithdroidFTextView*)visible;
- (FaithdroidFTextView*)x:(double)x;
- (FaithdroidFTextView*)y:(double)y;
@end

@interface FaithdroidFToolbar : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FToolbar.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FToolbar.MyMenu with unsupported type: []interface{}

// skipped method FToolbar.Assign with unsupported parameter or return types

- (FaithdroidFToolbar*)backNavigation:(BOOL)b;
- (FaithdroidFToolbar*)background:(NSString*)s;
- (FaithdroidFToolbar*)backgroundColor:(NSString*)s;
- (FaithdroidFToolbar*)cachedBackground:(NSString*)s;
- (FaithdroidFToolbar*)cachedForeground:(NSString*)s;
- (FaithdroidFToolbar*)clickable:(BOOL)b;
- (FaithdroidFToolbar*)elevation:(double)dp;
- (FaithdroidFToolbar*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFToolbar*)gone;
- (FaithdroidFToolbar*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFToolbar*)layoutGravity:(long)gravity;
- (FaithdroidFToolbar*)layoutWeight:(long)f;
- (FaithdroidFToolbar*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFToolbar*)marginAll:(long)dp;
- (FaithdroidFToolbar*)marginBottom:(long)dp;
- (FaithdroidFToolbar*)marginLeft:(long)dp;
- (FaithdroidFToolbar*)marginRight:(long)dp;
- (FaithdroidFToolbar*)marginTop:(long)dp;
// skipped method FToolbar.Menus with unsupported parameter or return types

- (FaithdroidFToolbar*)navigationIcon:(NSString*)i;
// skipped method FToolbar.OnClick with unsupported parameter or return types

// skipped method FToolbar.OnNavigationIconClick with unsupported parameter or return types

// skipped method FToolbar.OnTouch with unsupported parameter or return types

- (FaithdroidFToolbar*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFToolbar*)paddingAll:(long)dp;
- (FaithdroidFToolbar*)paddingBottom:(long)dp;
- (FaithdroidFToolbar*)paddingLeft:(long)dp;
- (FaithdroidFToolbar*)paddingRight:(long)dp;
- (FaithdroidFToolbar*)paddingTop:(long)dp;
- (FaithdroidFToolbar*)pivotX:(double)x;
- (FaithdroidFToolbar*)pivotY:(double)y;
// skipped method FToolbar.PopupMenu with unsupported parameter or return types

- (FaithdroidFToolbar*)rotation:(double)r;
- (FaithdroidFToolbar*)scaleX:(double)x;
- (FaithdroidFToolbar*)scaleY:(double)y;
- (FaithdroidFToolbar*)setId:(NSString*)s;
- (FaithdroidFToolbar*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FToolbar.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFToolbar*)size:(long)w h:(long)h;
- (FaithdroidFToolbar*)subtitle:(NSString*)s;
/**
 * ----------------------------------------------------------
 */
- (FaithdroidFToolbar*)title:(NSString*)s;
- (FaithdroidFToolbar*)visible;
- (FaithdroidFToolbar*)x:(double)x;
- (FaithdroidFToolbar*)y:(double)y;
@end

@interface FaithdroidFVScrollView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FVScrollView.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped field FVScrollView.Children with unsupported type: []github.com/gofaith/faithdroid.IView

- (FaithdroidFVScrollView*)addView:(id<FaithdroidIView>)i;
- (FaithdroidFVScrollView*)addViewAt:(id<FaithdroidIView>)i pos:(long)pos;
// skipped method FVScrollView.Append with unsupported parameter or return types

// skipped method FVScrollView.Assign with unsupported parameter or return types

- (FaithdroidFVScrollView*)background:(NSString*)s;
- (FaithdroidFVScrollView*)backgroundColor:(NSString*)s;
- (FaithdroidFVScrollView*)cachedBackground:(NSString*)s;
- (FaithdroidFVScrollView*)cachedForeground:(NSString*)s;
- (FaithdroidFVScrollView*)clickable:(BOOL)b;
- (FaithdroidFVScrollView*)deferShow;
- (FaithdroidFVScrollView*)elevation:(double)dp;
- (FaithdroidFVScrollView*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFVScrollView*)gone;
- (FaithdroidFVScrollView*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFVScrollView*)layoutGravity:(long)gravity;
- (FaithdroidFVScrollView*)layoutWeight:(long)f;
- (FaithdroidFVScrollView*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFVScrollView*)marginAll:(long)dp;
- (FaithdroidFVScrollView*)marginBottom:(long)dp;
- (FaithdroidFVScrollView*)marginLeft:(long)dp;
- (FaithdroidFVScrollView*)marginRight:(long)dp;
- (FaithdroidFVScrollView*)marginTop:(long)dp;
// skipped method FVScrollView.OnClick with unsupported parameter or return types

// skipped method FVScrollView.OnTouch with unsupported parameter or return types

- (FaithdroidFVScrollView*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFVScrollView*)paddingAll:(long)all;
- (FaithdroidFVScrollView*)paddingBottom:(long)dp;
- (FaithdroidFVScrollView*)paddingLeft:(long)dp;
- (FaithdroidFVScrollView*)paddingRight:(long)dp;
- (FaithdroidFVScrollView*)paddingTop:(long)dp;
- (FaithdroidFVScrollView*)pivotX:(double)x;
- (FaithdroidFVScrollView*)pivotY:(double)y;
// skipped method FVScrollView.PopupMenu with unsupported parameter or return types

- (FaithdroidFVScrollView*)rotation:(double)r;
- (FaithdroidFVScrollView*)scaleX:(double)x;
- (FaithdroidFVScrollView*)scaleY:(double)y;
- (FaithdroidFVScrollView*)setId:(NSString*)s;
- (FaithdroidFVScrollView*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FVScrollView.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFVScrollView*)size:(long)w h:(long)h;
- (FaithdroidFVScrollView*)visible;
- (FaithdroidFVScrollView*)x:(double)x;
- (FaithdroidFVScrollView*)y:(double)y;
@end

@interface FaithdroidFValueAnimator : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FValueAnimator.FBase with unsupported type: github.com/gofaith/faithdroid.FBase

- (FaithdroidFValueAnimator*)duration:(int64_t)ms;
- (NSString*)getViewId;
// skipped method FValueAnimator.OfFloat with unsupported parameter or return types

// skipped method FValueAnimator.OfInt with unsupported parameter or return types

// skipped method FValueAnimator.OnValueChanged with unsupported parameter or return types

- (FaithdroidFValueAnimator*)start;
@end

@interface FaithdroidFViewPager : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FViewPager.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

// skipped method FViewPager.Assign with unsupported parameter or return types

- (FaithdroidFViewPager*)background:(NSString*)s;
- (FaithdroidFViewPager*)backgroundColor:(NSString*)s;
- (FaithdroidFViewPager*)bindTabLayoutById:(NSString*)id_;
- (FaithdroidFViewPager*)cachedBackground:(NSString*)s;
- (FaithdroidFViewPager*)cachedForeground:(NSString*)s;
- (FaithdroidFViewPager*)clickable:(BOOL)b;
- (FaithdroidFViewPager*)currentItem:(long)i soomth:(BOOL)soomth;
- (FaithdroidFViewPager*)elevation:(double)dp;
- (FaithdroidFViewPager*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFViewPager*)gone;
- (FaithdroidFViewPager*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFViewPager*)layoutGravity:(long)gravity;
- (FaithdroidFViewPager*)layoutWeight:(long)f;
- (FaithdroidFViewPager*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFViewPager*)marginAll:(long)dp;
- (FaithdroidFViewPager*)marginBottom:(long)dp;
- (FaithdroidFViewPager*)marginLeft:(long)dp;
- (FaithdroidFViewPager*)marginRight:(long)dp;
- (FaithdroidFViewPager*)marginTop:(long)dp;
// skipped method FViewPager.OnClick with unsupported parameter or return types

// skipped method FViewPager.OnGetPage with unsupported parameter or return types

// skipped method FViewPager.OnPageSelected with unsupported parameter or return types

// skipped method FViewPager.OnTouch with unsupported parameter or return types

- (FaithdroidFViewPager*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFViewPager*)paddingAll:(long)all;
- (FaithdroidFViewPager*)paddingBottom:(long)dp;
- (FaithdroidFViewPager*)paddingLeft:(long)dp;
- (FaithdroidFViewPager*)paddingRight:(long)dp;
- (FaithdroidFViewPager*)paddingTop:(long)dp;
// skipped method FViewPager.Pages with unsupported parameter or return types

- (FaithdroidFViewPager*)pivotX:(double)x;
- (FaithdroidFViewPager*)pivotY:(double)y;
// skipped method FViewPager.PopupMenu with unsupported parameter or return types

- (FaithdroidFViewPager*)rotation:(double)r;
- (FaithdroidFViewPager*)scaleX:(double)x;
- (FaithdroidFViewPager*)scaleY:(double)y;
- (FaithdroidFViewPager*)setId:(NSString*)s;
- (FaithdroidFViewPager*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FViewPager.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFViewPager*)size:(long)w h:(long)h;
- (FaithdroidFViewPager*)visible;
- (FaithdroidFViewPager*)x:(double)x;
- (FaithdroidFViewPager*)y:(double)y;
@end

@interface FaithdroidFWebView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field FWebView.FBaseView with unsupported type: github.com/gofaith/faithdroid.FBaseView

- (FaithdroidFWebView*)allowContentAccess:(BOOL)b;
- (FaithdroidFWebView*)allowFileAccess:(BOOL)b;
- (FaithdroidFWebView*)allowFileAccessFromFileURLs:(BOOL)b;
- (FaithdroidFWebView*)allowUniversalAccessFromFileURLs:(BOOL)b;
- (FaithdroidFWebView*)appCacheEnabled:(BOOL)b;
// skipped method FWebView.Assign with unsupported parameter or return types

- (FaithdroidFWebView*)background:(NSString*)s;
- (FaithdroidFWebView*)backgroundColor:(NSString*)s;
- (FaithdroidFWebView*)blockNetworkImage:(BOOL)b;
- (FaithdroidFWebView*)blockNetworkLoads:(BOOL)b;
- (FaithdroidFWebView*)builtInZoomControls:(BOOL)b;
- (FaithdroidFWebView*)cachedBackground:(NSString*)s;
- (FaithdroidFWebView*)cachedForeground:(NSString*)s;
- (FaithdroidFWebView*)clickable:(BOOL)b;
- (FaithdroidFWebView*)elevation:(double)dp;
- (FaithdroidFWebView*)focusable:(BOOL)b;
- (FaithdroidFWebView*)foreground:(NSString*)s;
- (double)getHeight;
- (double)getPivotX;
- (double)getPivotY;
- (double)getRotation;
- (double)getScaleX;
- (double)getScaleY;
- (NSString*)getViewId;
- (double)getWidth;
- (double)getX;
- (double)getY;
- (FaithdroidFWebView*)gone;
// skipped method FWebView.HandleUrl with unsupported parameter or return types

- (FaithdroidFWebView*)invisible;
- (BOOL)isGone;
- (BOOL)isInvisible;
- (BOOL)isVisible;
- (FaithdroidFWebView*)javaScriptEnabled:(BOOL)b;
- (FaithdroidFWebView*)layoutGravity:(long)gravity;
- (FaithdroidFWebView*)layoutWeight:(long)f;
- (FaithdroidFWebView*)loadHtmlData:(NSString*)s;
- (FaithdroidFWebView*)margin:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFWebView*)marginAll:(long)dp;
- (FaithdroidFWebView*)marginBottom:(long)dp;
- (FaithdroidFWebView*)marginLeft:(long)dp;
- (FaithdroidFWebView*)marginRight:(long)dp;
- (FaithdroidFWebView*)marginTop:(long)dp;
- (FaithdroidFWebView*)offscreenPreRaster:(BOOL)b;
// skipped method FWebView.OnClick with unsupported parameter or return types

// skipped method FWebView.OnDownload with unsupported parameter or return types

// skipped method FWebView.OnTouch with unsupported parameter or return types

- (FaithdroidFWebView*)padding:(long)left top:(long)top right:(long)right bottom:(long)bottom;
- (FaithdroidFWebView*)paddingAll:(long)dp;
- (FaithdroidFWebView*)paddingBottom:(long)dp;
- (FaithdroidFWebView*)paddingLeft:(long)dp;
- (FaithdroidFWebView*)paddingRight:(long)dp;
- (FaithdroidFWebView*)paddingTop:(long)dp;
- (FaithdroidFWebView*)pivotX:(double)x;
- (FaithdroidFWebView*)pivotY:(double)y;
// skipped method FWebView.PopupMenu with unsupported parameter or return types

- (FaithdroidFWebView*)rotation:(double)r;
- (FaithdroidFWebView*)saveFormData:(BOOL)b;
- (FaithdroidFWebView*)scaleX:(double)x;
- (FaithdroidFWebView*)scaleY:(double)y;
- (FaithdroidFWebView*)setId:(NSString*)s;
- (FaithdroidFWebView*)setItemId:(FaithdroidFListView*)parent id_:(NSString*)id_;
- (void)show;
// skipped method FWebView.ShowPopupMenu with unsupported parameter or return types

- (FaithdroidFWebView*)size:(long)w h:(long)h;
- (FaithdroidFWebView*)supportMultipleWindows:(BOOL)b;
- (FaithdroidFWebView*)supportZoom:(BOOL)b;
- (FaithdroidFWebView*)textZoom:(long)i;
- (FaithdroidFWebView*)useWideViewPort:(BOOL)b;
- (FaithdroidFWebView*)userAgentString:(NSString*)s;
- (FaithdroidFWebView*)visible;
- (FaithdroidFWebView*)x:(double)x;
- (FaithdroidFWebView*)y:(double)y;
@end

/**
 * Intent
 */
@interface FaithdroidIntent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)action;
- (void)setAction:(NSString*)v;
// skipped field Intent.Paths with unsupported type: []string

// skipped field Intent.Extras with unsupported type: map[string]string

@end

/**
 * MainActivity
 */
@interface FaithdroidMainActivity : NSObject <goSeqRefInterface, FaithdroidIActivity> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
// skipped field MainActivity.Activity with unsupported type: github.com/gofaith/faithdroid.Activity

- (void)addPath:(NSString*)s;
- (NSString*)getAllExtras;
- (NSString*)getContext;
- (NSString*)getExtraValue:(NSString*)key;
- (NSString*)getIntentAction;
- (FaithdroidActivity*)getMyActivity;
- (NSString*)getPathArray:(NSString*)s;
- (void)onCreate;
- (void)onDestroy;
- (void)onPause;
- (void)onResume;
- (void)onStart;
- (void)putExtra:(NSString*)key value:(NSString*)value;
- (void)setIntentAction:(NSString*)s;
- (NSString*)setUIInterface:(id<FaithdroidUIController>)u;
@end

@interface FaithdroidTouchEvent : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (double)x;
- (void)setX:(double)v;
- (double)y;
- (void)setY:(double)v;
- (NSString*)action;
- (void)setAction:(NSString*)v;
@end

@interface FaithdroidTypeOnBindDataArgsBundle : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)str;
- (void)setStr:(NSString*)v;
- (long)position;
- (void)setPosition:(long)v;
@end

/**
 * ViewHolder
 */
@interface FaithdroidViewHolder : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
- (NSString*)vid;
- (void)setVID:(NSString*)v;
// skipped field ViewHolder.Vlist with unsupported type: map[string]string

- (FaithdroidFButton*)getButtonByItemId:(NSString*)id_;
- (FaithdroidFCheckBox*)getCheckBoxByItemId:(NSString*)id_;
- (FaithdroidFEditText*)getEditTextByItemId:(NSString*)id_;
- (FaithdroidFBottomNav*)getFBottomNavByItemId:(NSString*)id_;
- (FaithdroidFFab*)getFabByItemId:(NSString*)id_;
- (FaithdroidFFrameLayout*)getFrameLayoutByItemId:(NSString*)id_;
- (FaithdroidFHScrollView*)getHScrollViewByItemId:(NSString*)id_;
- (FaithdroidFImageView*)getImageViewByItemId:(NSString*)id_;
- (FaithdroidFLinearLayout*)getLinearLayoutByItemId:(NSString*)id_;
- (FaithdroidFListView*)getListViewByItemId:(NSString*)id_;
- (FaithdroidFRadioButton*)getRadioButtonByItemId:(NSString*)id_;
- (FaithdroidFRadioGroup*)getRadioGroupByItemId:(NSString*)id_;
- (FaithdroidFSpace*)getSpaceByItemId:(NSString*)id_;
- (FaithdroidFSpinner*)getSpinnerByItemId:(NSString*)id_;
- (FaithdroidFSwitch*)getSwitchByItemId:(NSString*)id_;
- (FaithdroidFTabLayout*)getTabLayoutByItemId:(NSString*)id_;
- (FaithdroidFTextView*)getTextViewByItemId:(NSString*)id_;
- (FaithdroidFVScrollView*)getVScrollViewByItemId:(NSString*)id_;
- (FaithdroidFViewPager*)getViewPagerByItemId:(NSString*)id_;
- (FaithdroidFWebView*)getWebViewByItemId:(NSString*)id_;
@end

@interface Faithdroid : NSObject
// skipped variable Colors with unsupported type: github.com/gofaith/faithdroid.ColorsCollection

// skipped variable GlobalVars with unsupported type: struct{IdMap map[string]github.com/gofaith/faithdroid.IView; ViewMap map[string]github.com/gofaith/faithdroid.IView; EventHandlersMap map[string]func(string) string; UIs map[string]github.com/gofaith/faithdroid.UIController}

// skipped variable Gravitys with unsupported type: struct{Left int; Right int; Top int; Bottom int; Center int; CenterHorizontal int; CenterVertical int}

// skipped variable IntentActions with unsupported type: struct{VIEW string; SEND string; SEND_MULTIPLE string}

// skipped variable Permissions with unsupported type: struct{CAMERA string; WRITE_EXTERNAL_STORAGE string; READ_EXTERNAL_STORAGE string; READ_PHONE_STATE string; READ_CALENDAR string; WRITE_CALENDAR string; READ_CONTACTS string; WRITE_CONTACTS string; GET_ACCOUNTS string; ACCESS_FINE_LOCATION string; ACCESS_COARSE_LOCATION string; RECORD_AUDIO string; CALL_PHONE string; READ_CALL_LOG string; WRITE_CALL_LOG string; ADD_VOICEMAIL string; USE_SIP string; PROCESS_OUTGOING_CALLS string; BODY_SENSORS string; SEND_SMS string; RECEIVE_SMS string; READ_SMS string; RECEIVE_WAP_PUSH string; RECEIVE_MMS string}

// skipped variable ScaleTypes with unsupported type: struct{Center string; CenterCrop string; CenterInside string; FitCenter string; FitStart string; FitEnd string; FitXY string; Matrix string}

@end

FOUNDATION_EXPORT FaithdroidFAlertDialog* FaithdroidAlertDialog(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFBottomNav* FaithdroidBottomNav(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFBuild* FaithdroidBuild(FaithdroidActivity* a);

FOUNDATION_EXPORT FaithdroidFButton* FaithdroidButton(id<FaithdroidIActivity> a);

// skipped function CacheNetFile with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFCheckBox* FaithdroidCheckBox(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT BOOL FaithdroidCheckSelfPermission(id<FaithdroidIActivity> a, NSString* permission);

FOUNDATION_EXPORT FaithdroidFClipboard* FaithdroidClipboard(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT BOOL FaithdroidDownloadFile(NSString* url, NSString* fdist, NSError** error);

// skipped function DownloadNetFile with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFEditText* FaithdroidEditText(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT BOOL FaithdroidEndsWith(NSString* s, NSString* suffix);

FOUNDATION_EXPORT FaithdroidFFab* FaithdroidFab(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT void FaithdroidFinish(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFFrameLayout* FaithdroidFrameLayout(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFBottomNav* FaithdroidGetBottomNavById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFButton* FaithdroidGetButtonById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFCheckBox* FaithdroidGetCheckBoxById(NSString* id_);

FOUNDATION_EXPORT NSString* FaithdroidGetDirOfFile(NSString* f);

FOUNDATION_EXPORT FaithdroidFEditText* FaithdroidGetEditTextById(NSString* id_);

FOUNDATION_EXPORT NSString* FaithdroidGetExternalStorageDirectory(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFFab* FaithdroidGetFabById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFFrameLayout* FaithdroidGetFrameLayoutById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFHScrollView* FaithdroidGetHScrollViewById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFImageView* FaithdroidGetImageViewById(NSString* id_);

// skipped function GetInstalledApps with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFLinearLayout* FaithdroidGetLinearLayoutById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFListView* FaithdroidGetListViewById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFRadioButton* FaithdroidGetRadioButtonById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFRadioGroup* FaithdroidGetRadioGroupById(NSString* id_);

FOUNDATION_EXPORT NSString* FaithdroidGetRealUrl(NSString* url);

FOUNDATION_EXPORT FaithdroidFSpace* FaithdroidGetSpaceById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFSpinner* FaithdroidGetSpinnerById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFSwitch* FaithdroidGetSwitchById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFTabLayout* FaithdroidGetTabLayoutById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFTextView* FaithdroidGetTextViewById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFToolbar* FaithdroidGetToolbarById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFVScrollView* FaithdroidGetVScrollViewById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFViewPager* FaithdroidGetViewPagerById(NSString* id_);

FOUNDATION_EXPORT FaithdroidFWebView* FaithdroidGetWebViewById(NSString* id_);

FOUNDATION_EXPORT NSString* FaithdroidGetrpath(NSString* s);

FOUNDATION_EXPORT NSString* FaithdroidGuessFileName(id<FaithdroidIActivity> a, NSString* url);

// skipped function HListView with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFHScrollView* FaithdroidHScrollView(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFImageView* FaithdroidImageView(id<FaithdroidIActivity> a);

// skipped function JsonArray with unsupported parameter or return types


// skipped function JsonObject with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFLinearLayout* FaithdroidLinearLayout(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFMenuItem* FaithdroidMenuItem(NSString* title);

FOUNDATION_EXPORT FaithdroidActivityConfig* FaithdroidNewActivityConfig(void);

FOUNDATION_EXPORT NSString* FaithdroidNewNumToken(void);

FOUNDATION_EXPORT NSString* FaithdroidNewToken(void);

FOUNDATION_EXPORT void FaithdroidOpenFile(id<FaithdroidIActivity> a, NSString* path);

// skipped function OpenFileChooser with unsupported parameter or return types


// skipped function Page with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFRadioButton* FaithdroidRadioButton(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFRadioGroup* FaithdroidRadioGroup(id<FaithdroidIActivity> a);

// skipped function RequestPermissions with unsupported parameter or return types


// skipped function RunOnUIThread with unsupported parameter or return types


// skipped function SPrintf with unsupported parameter or return types


FOUNDATION_EXPORT void FaithdroidSaveDrawableToPNGFile(id<FaithdroidIActivity> a, NSString* drawableID, NSString* distPath);

FOUNDATION_EXPORT void FaithdroidScanFile(id<FaithdroidIActivity> a, NSString* fpath);

FOUNDATION_EXPORT void FaithdroidShowSnackbar(id<FaithdroidIActivity> a, NSString* s);

// skipped function ShowSnackbarWithAction with unsupported parameter or return types


FOUNDATION_EXPORT void FaithdroidShowToast(id<FaithdroidIActivity> a, NSString* s);

FOUNDATION_EXPORT FaithdroidFSnackbar* FaithdroidSnackbar(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFSpace* FaithdroidSpace(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFSpinner* FaithdroidSpinner(id<FaithdroidIActivity> a);

// skipped function StartActivity with unsupported parameter or return types


// skipped function StartService with unsupported parameter or return types


FOUNDATION_EXPORT void FaithdroidStartUriIntent(id<FaithdroidIActivity> a, NSString* uri);

// skipped function SubMenu with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFSwitch* FaithdroidSwitch(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFTab* FaithdroidTab(NSString* text);

FOUNDATION_EXPORT FaithdroidFTabLayout* FaithdroidTabLayout(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFTextView* FaithdroidTextView(id<FaithdroidIActivity> a);

/**
 * --------------------------------------------------------------------------------
 */
FOUNDATION_EXPORT FaithdroidFToolbar* FaithdroidToolbar(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT NSString* FaithdroidTriggerEventHandler(NSString* eID, NSString* args);

// skipped function UnJson with unsupported parameter or return types


FOUNDATION_EXPORT NSString* FaithdroidUriAssets(NSString* a);

FOUNDATION_EXPORT NSString* FaithdroidUriRes(NSString* a);

FOUNDATION_EXPORT NSString* FaithdroidUrl2cachePath(NSString* url);

// skipped function VListView with unsupported parameter or return types


FOUNDATION_EXPORT FaithdroidFVScrollView* FaithdroidVScrollView(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFValueAnimator* FaithdroidValueAnimator(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFViewPager* FaithdroidViewPager(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFWebView* FaithdroidWebView(id<FaithdroidIActivity> a);

FOUNDATION_EXPORT FaithdroidFWebView* FaithdroidWebViewItem(id<FaithdroidIActivity> a, NSString* uri);

// skipped function WriteFile with unsupported parameter or return types


FOUNDATION_EXPORT NSString* FaithdroidXPrintf(long a);

@class FaithdroidIActivity;

@class FaithdroidIView;

@class FaithdroidUIController;

/**
 * IActivity
 */
@interface FaithdroidIActivity : NSObject <goSeqRefInterface, FaithdroidIActivity> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (FaithdroidActivity*)getMyActivity;
@end

@interface FaithdroidIView : NSObject <goSeqRefInterface, FaithdroidIView> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (NSString*)getViewId;
@end

@interface FaithdroidUIController : NSObject <goSeqRefInterface, FaithdroidUIController> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)append2RootView:(NSString*)VID;
- (FaithdroidActivity*)getCurrentFActivity;
- (NSString*)getPkg;
- (void)newView:(NSString*)viewName VID:(NSString*)VID;
- (void)runUIThread:(NSString*)fnID;
- (NSString*)viewGetAttr:(NSString*)VID attr:(NSString*)attr;
- (void)viewSetAttr:(NSString*)VID attr:(NSString*)attr value:(NSString*)value;
@end

#endif
